#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${CONTACT_API_DB_USER} WITH PASSWORD '${CONTACT_API_DB_PASSWORD}';
    CREATE DATABASE ${CONTACT_API_DB_NAME} OWNER ${CONTACT_API_DB_USER};
    CREATE DATABASE ${CONTACT_API_DB_NAME}_test OWNER ${CONTACT_API_DB_USER};
EOSQL
