#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${OPENFGA_DB_USER} WITH PASSWORD '${OPENFGA_DB_PASSWORD}';
    CREATE DATABASE ${OPENFGA_DB_NAME} OWNER ${OPENFGA_DB_USER};
EOSQL
